### ISSUE TITLE
Audience should not be client_id

### ISSUE THREAD

**Issue by pushpabrol** [auth0-samples/auth0-aspnet-owin-webapi-sample#3]
See, https://github.com/auth0-samples/auth0-aspnet-owin-webapi-sample/blob/master/01-Authentication-RS256/WebApi/WebApi/Startup.cs#L21 - The audience is set to the client_id of the client app but the audience for that token should be the identifier of the actual API/Resource Server so a call to the API will always return a 401

**Comment by chenkie** [comment]
@jerriep can you take a look?

**Comment by jerriep** [comment]
@pushpabrol and @chenkie 

The entire folder "01-Authentication-RS256" should be removed, but I cannot since the latest docs have not been deployed yet which points to the correct folder structures.

The correct folders in that sample are:
* 00-Starter-Seed
* 01-Authentication
* 02-Authorization
* 03-Authentication-HS256
* 04-Authentication-RS256-Deprecated
* 05-Authentication-HS256-Deprecated
* 06-Authorization-Deprecated

So the correct one is this one:
https://github.com/auth0-samples/auth0-aspnet-owin-webapi-sample/blob/master/01-Authentication/WebApi/WebApi/Startup.cs#L26
